#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# {
#     'sslhosts': ['ssl.test.com', 'sslserver2.test.com']
#     'timeout': '180',
# }

# 'sslhost', timeout

def agent_ssllabs_arguments(params, _hostname, _ipaddress):
    args = []

    if 'sslhosts' in params:
        args += ['--sslhosts', ','.join(params['sslhosts'])]

    if 'timeout' in params:
        args += ['--timeout', params['timeout']]

    if 'proxy' in params:
        args += ['--proxy', params['proxy']]

    if 'publishresults' in params:
        args += ['--publish', params['publishresults']]

    if 'maxage' in params:
        args += ['--maxage', params['maxage']]

    return args


special_agent_info['ssllabs'] = agent_ssllabs_arguments
